print("{:^45}".format('TOKO MAINAN ANAK'))
print("{:^45}".format('********************'))

nama_pembeli = input("Masukan Nama Pembeli :")
kode_mainan = input("Masukan Kode Mainan :")
harga = int(input("Masukan Harga :"))
jumlah = int(input("Masukan Jumlah beli :"))
total = (harga*jumlah)
print("=================================")
print("Nama Pembeli =", (nama_pembeli))
print("Kode Mainan  =", (kode_mainan))
print("Harga        =", (harga))
print("Jumlah Beli  =", (jumlah))
print("Total        =", (total))
